### ISSUE TITLE
Last version not published on `crates.io`

### ISSUE THREAD

**Issue by Luni-4** [ivmarkov/edge-net#23]
I've just noticed that `v0.7.1` version has not been published on`crates.io`, but README's badges say differently. Is that an internal choice for the project?

**Comment by ivmarkov** [comment]
No, it is an internal choice of doing too many things and not having enough time.

Will try to publish by EOW and once done will close this. :)

**Comment by Luni-4** [comment]
Ahhh, I see now. Thanks a lot! :)

**Comment by ivmarkov** [comment]
All published!
