### ISSUE TITLE
[edge-dhcp]: Not sending DHCP Offer packets when running with embassy.

### ISSUE THREAD

**Issue by AnthonyGrondin** [ivmarkov/edge-net#27]
I'm trying to setup a DHCP server on `esp32s3` using embassy-net, and whilst the server logs sending DHCP Offer packets, I can't see them getting transmitted on the wire.

Wireshark capture:
![image](https://github.com/user-attachments/assets/f2e7e96c-1166-4a98-92b6-bbe20dccfaa1)

Example code:
```rust
info!("DHCP server starting");

let ip = Ipv4Addr::new(192, 168, 11, 1);

let buffers = UdpBuffers::<1, 1500, 1500, 2>::new();
let udp = Udp::new(&stack, &buffers);

let mut tx_buf = [0u8; 1500];
let mut rx_buf = [0u8; 1500];

let mut socket = udp
    .bind(SocketAddr::new(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 67))
    .await
    .unwrap();

info!("DHCP server bound to port 67.");

let mut server = edge_dhcp::server::Server::<64>::new(ip);
let mut gw_buf = [Ipv4Addr::UNSPECIFIED];
let server_options = ServerOptions::new(ip, Some(&mut gw_buf));

let mut buf = [0u8; 1500];

loop {
    match edge_dhcp::io::server::run(
        &mut server,
        &server_options,
        &mut socket,
        &mut buf,
    )
    .await
    {
        Ok(_) => todo!(),
        Err(_) => todo!(),
    }
}
```

**Comment by ivmarkov** [comment]
Not in front of my PC currently, but I vaguely remember `embassy-net` not liking `Ipv4Addr::UNSPECIFIED` when sending to a broadcast address (dhcp-server almost always replies with its offers using broadcasting).

In any case `dhcp-server` should work with `embassy-net`. If you browse the embassy Matrix channel, Michael K. was running the server several months ago.

**Comment by ivmarkov** [comment]
@AnthonyGrondin Actually, the DHCP server should work fine with `Ipv4Addr::UNSPECIFIED`, as [I have fixed that](https://github.com/ivmarkov/edge-net/commit/5720209dfce376662d09bfc56c68f28f6d603002) after a discussion with @MathiasKoch

**Comment by AnthonyGrondin** [comment]
Turns out it was an oversight on my part. I was running embassy + esp_wifi in AP config, but in my wifi driver, I didn't pass a static IP config to embassy-net. I'm surprised it didn't fail with any error whatsoever.
