### ISSUE TITLE
`edge-http`: `no_std` support for `x86_64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by polarathene** [ivmarkov/edge-net#39]
At a glance creating a `no_std` HTTP client for this target is limited by some features being tied to Rust `std` lib.

- From what I understand though, `rustix` may implement a `libc`-free way to workaround that for `no_std`? (_for example [`bind`](https://github.com/bytecodealliance/rustix/blob/7d4a719f33495c45ba74a3a8fb7a16bf737f8036/src/net/socket.rs#L99-L134)_)
- I'm not sure when I'll get time to explore this, but if anyone knows if this is actually feasible / worthwhile, that'd be good to know.
- Presently I can produce a simple HTTP client to perform a `GET` request over `http://` (130KB) or `https://` (770KB).

I am curious if [`edge-http`](https://github.com/ivmarkov/edge-net/tree/master/edge-http) could be leveraged to perform that functionality with `no_std` for a static `-gnu` (Eyra) or `-musl` target. From what I can gather, a driver should be implemented with `smoltcp` / `embassy-net`?

**Comment by ivmarkov** [comment]
I don't follow, if you could elaborate what you are trying to achieve?

**In general though**: 
`http-client` is `no_std` in that it does not really _DIRECTLY_ use or reference neither the Standard library, nor the `alloc` one (but it can still sit on top of STD - read on). So as long as you provide to it something which implements `embedded_io_async::Read + Write`, it would be happy (that is, the `io` module).
If you want to take advantage of the HTTP `io::client` module and its re-connection capabilities, you need to provide an implementation of the `edge_nal::TcpConnect` trait. In general, how you'd implement it is up to you, and `edge-http` does not care.

With that said, there are two out-of-the box implementations of the `edge-nal` traits:
- For Rust STD, in `edge-nal-std`
- For Embassy, in `edge-nal-embassy`

**Where I struggle with in your elaboration**:
> At a glance creating a no_std HTTP client for this target (x86_64-unknown-linux-gnu) is limited by some features being tied to Rust std lib.

I do not understand why you'd want to do this. `x86_64-unknown-linux-gnu` IS a "std" target, in that it sits on top of the `glibc` library, and as such I don't understand why you'd want to bypass the C library. What would you do instead? Direct calls to the kernel?

> From what I understand though, rustix may implement a libc-free way to workaround that for no_std? (for example [bind](https://github.com/bytecodealliance/rustix/blob/7d4a719f33495c45ba74a3a8fb7a16bf737f8036/src/net/socket.rs#L99-L134))

Whether you use the `rustix` crate directly, or the `libc` crate directly, or still the `libc` crate indirectly via Rust STD (the Rust Standard Library is nothing else but 0-cost type-safe wrappers around `libc`), you are still - in the end - _hitting the C library_ (glibc in the case of `x86_64-unknown-linux-gnu`). So why you'd want to hit glibc with `rustix` and not via `libc` or STD is weird

> I am curious if [edge-http](https://github.com/ivmarkov/edge-net/tree/master/edge-http) could be leveraged to perform that functionality with no_std for a static -gnu (Eyra) or -musl target. From what I can gather, a driver should be implemented with smoltcp / embassy-net?

Both of static -gnu and -musl targets still have a standard C library. In the musl case, the library is `musl` but no big deal. Rust STD still works on top of it, and so will `edge-http`, with the `edge-nal-std` adaptor.

**Comment by polarathene** [comment]
> What would you do instead? Direct calls to the kernel?

Yes, through `rustix` which abstracts that.

> Whether you use the `rustix` crate directly, or the `libc` crate directly, or still the `libc` crate indirectly via Rust STD (the Rust Standard Library is nothing else but 0-cost type-safe wrappers around `libc`), you are still - in the end - _hitting the C library_ (glibc in the case of `x86_64-unknown-linux-gnu`). So why you'd want to hit glibc with `rustix` and not via `libc` or STD is weird

Perhaps I'm misunderstanding something, but I've seen 800KB (glibc) / 25KB (musl) with `std` vs 456 bytes with `rustix` and `no_std`.

I assume skipping `std` in favor of `rustix` for the same functionality would likewise enable such reductions?

## Hello World `std` / `no_std` / `core` + `rustix`

A "Hello World" (`cargo init`) the equivalent with `std` / `libc` on this target is over 800KB for a static glibc build. With the musl target it's about 25KB.

Both are built with the same cargo flags and profile optimizations to cut down on that (_LTO is enabled, so is `strip = true`_), which with `-Z build-std` and panic abort makes quite the reduction for musl (_390KB => 25KB_):

```console
$ RUSTFLAGS="-Z location-detail=none -C relocation-model=static -C target-feature=+crt-static" cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-musl --release

$ du --bytes target/x86_64-unknown-linux-musl/release/example
30288   target/x86_64-unknown-linux-musl/release/example

# NOTE:
# 24,984 bytes with `-C link-arg=-fuse-ld=lld`
# 389,744 bytes with LLD and without `-Z build-std` args
```

When minimizing `libc` usage and switching to `no_std` (_`write()` still belongs to the static linked `libc`_):

```rust
#![no_std]
#![no_main]

#[no_mangle]
pub extern "C" fn main() -> isize {
    const HELLO: &'static str = "Hello, world!\n";
    unsafe { write(1, HELLO.as_ptr() as *const i8, HELLO.len()) };
    0
}

extern "C" {
    fn write(fd: i32, buf: *const i8, count: usize) -> isize;
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! { loop {} }
```

A build with static glibc is still at 693KB, while musl gets down to 3-4KB.

However once `libc` is completely out of the picture, it no longer matters if the target is `-gnu` or `-musl`. This is only **456 bytes**:

```rust
#![no_std]
#![no_main]

#[no_mangle]
pub extern "C" fn _start() -> ! {
  hello_world()
  exit();
}

#[inline(always)]
fn hello_world() {
  rustix::io::write(
    unsafe { rustix::stdio::stdout() },
    "Hello, world!\n".as_bytes()
  ).unwrap();
}

fn exit() -> ! { unsafe { rustix::runtime::exit_thread(42) } }

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! { loop {} }
```

```console
$ RUSTFLAGS='-C link-arg=-Wl,--build-id=none,--omagic,-z,nognustack -C link-arg=-fuse-ld=lld -C relocation-model=static -C target-feature=+crt-static -C link-arg=-nostartfiles' \
  cargo build --release --target x86_64-unknown-linux-gnu \
  -Z build-std=core,panic_abort \
  -Z build-std-features=panic_immediate_abort

$ objcopy -R .comment target/x86_64-unknown-linux-gnu/release/example

$ du --bytes target/x86_64-unknown-linux-gnu/release/example
456     target/x86_64-unknown-linux-gnu/release/example

$ ldd target/x86_64-unknown-linux-gnu/release/example
        not a dynamic executable

$ target/x86_64-unknown-linux-gnu/release/example
Hello, world!
```

---

> Both of static -gnu and -musl targets still have a standard C library

I think I've clarified from the above any misunderstanding and where my interest is?

Would it be right to assume that not relying on `std` and instead leveraging `rustix` at a lower level, would likewise trim down the size for use with `edge-http`?

Or with your expertise in this area would I be mistaken and there isn't likely to be as much of a reduction from the `std` based 130KB HTTP client build size on this platform? (_this size is from using the `minreq` crate_)

If it seems like a reasonable reduction could be accomplished for amd64 linux, and `edge-http` would be good to accomplish that along with implementing a driver via `smoltcp` / `embassy`, I could give that a shot :)

Just reaching out for a sanity check if I'm on the right track 😅

**Comment by ivmarkov** [comment]
> > I don't follow, if you could elaborate what you are trying to achieve?
> 
> I'm curious by how much I could reduce the size of an HTTP / HTTPS client further for amd64 linux platform than I've currently cited.
> 
> It's not super important or high priority. I'm quite happy with the size as is, it's just for adding into a container for a healthcheck.

Now I understand.

> 
> > What would you do instead? Direct calls to the kernel?
> 
> Yes, through `rustix` which abstracts that.

That was the **key**. 
Sorry, I did not realize, that `rustix` does have the "linux-raw" backend, which does exactly that - goes straight to the kernel, bypassing the Standard C library completely! Moreover, it seems to be enabled by default.

> I think I've clarified from the above any misunderstanding and where my interest is?

Yes.

> Would it be right to assume that not relying on `std` and instead leveraging `rustix` at a lower level, would likewise trim down the size for use with `edge-http`?

Yes!

> Or with your expertise in this area would I be mistaken and there isn't likely to be as much of a reduction from the `std` based 130KB HTTP client build size on this platform? (_this size is from using the `minreq` crate_)

Yes, it seems you can reduce quite a bit by skipping libc.

> If it seems like a reasonable reduction could be accomplished for amd64 linux, and `edge-http` would be good to accomplish that along with implementing a driver via `smoltcp` / `embassy`, I could give that a shot :)

**This is where I'm not sure**. 
The thing is, `smoltcp` + `embassy-net` both run their own TCP/IP stack implemented from scratch. They only expect an "ethernet" device. I.e. a "tap" like thing via which you can pull/push ethernet packets.

Why would you want to do this, if you have the TCP/IP stack underneath inside the Linux kernel (that is, unless you compile the kernel without TCP/IP support - if that's _even_ possible)?

Moreover, your executable might be smaller by actually calling (via `rustix`) into the kernel TCP/IP stack, rather than implementing it on your own. The best way to implement this is simply in the form of a `edge-nal-rustix` crate, that implements the `edge-nal` abstractions by going straight into `rustix` and thus straight into the kernel.

By basing your solution on top of `smoltcp`, your executable _might_ be larger, because you'll have the kernel TCP/IP stack lying around, _plus_ your own TCP/IP stack in your own executable.


With all of that said, I'm unsure why trimming the executable from a few tens of kilos or even from a few hundreds of kilos to a few hundreds of bytes on what usually is a machine with at least half a gig of RAM and many gigs of of storage (i.e. your usual embedded Linux SOC) matters.

But perhaps I'm missing an important detail!

**Comment by polarathene** [comment]
> Moreover, it seems to be enabled by default.

Yeah, but you still need to provide a `linux-gnu` / `linux-musl` target for it to do so, `x86_64-uknown-none` lacks the `linux` context and there is no `linux-none` target, although it's effectively not using glibc or musl I can see the choice in target can seem a tad misleading 😅 

> Yes, it seems you can reduce quite a bit by skipping libc.

Given the 3-4KB musl `no_std` example, I think bringing in libc itself is ok. Something about glibc though prevents static linking from trimming out the fat via LTO, I'm guessing due to something like `dl_open`.

The "Hello World" std example with musl did go from 390KB down to 25KB, and I had used the same approach for the `minreq` crate to build down to 130KB. Thus I'm not quite sure how much of that extra 100KB could be stripped down further by avoiding `libstd`.

Perhaps 10-50KB would be reasonable to expect, I'm more curious with the HTTPS variant reducing down from 770KB, but I've not yet checked what `edge-net` with a `no_std` target and `embedded-tls` compile to (_with any of the existing options_). I assume it's  smaller than `no_std` Rustls.

---

> **This is where I'm not sure**. The thing is, `smoltcp` + `embassy-net` both run their own TCP/IP stack implemented from scratch. They only expect an "ethernet" device. I.e. a "tap" like thing via which you can pull/push ethernet packets.
> 
> Why would you want to do this, if you have the TCP/IP stack underneath inside the Linux kernel (that is, unless you compile the kernel without TCP/IP support - if that's _even_ possible)?

Ah, well this is where I wasn't sure about the correct approach as I'm fairly inexperienced in this area. I thought those crates were going to make it simpler to implement 😓 

I know from the crates like `minreq` that `std::net` is used for TCP binding and stream, and another dependency on std for `Duration`. Embassy had it's own time solution IIRC, but I think that was still reliant upon an implementation for each platform. Similarly the traits for implementing the TCP stack parts, so I thought I'd just be hooking `rustix` up into that.

That does make sense though for why there was a TUN driver example only for amd64 linux 🤔 

> Moreover, your executable might be smaller by actually calling (via `rustix`) into the kernel TCP/IP stack, rather than implementing it on your own.
> The best way to implement this is simply in the form of a `edge-nal-rustix` crate, that implements the `edge-nal` abstractions by going straight into `rustix` and thus straight into the kernel.

Ah ok, so skip `smoltcp` and `embassy` entirely? I can just use `rustix` and the `edge` ecosystem of crates?

---

> By basing your solution on top of `smoltcp`, your executable _might_ be larger, because you'll have the kernel TCP/IP stack lying around, _plus_ your own TCP/IP stack in your own executable.

> With all of that said, I'm unsure why trimming the executable from a few tens of kilos or even from a few hundreds of kilos to a few hundreds of bytes on what usually is a machine with at least half a gig of RAM and many gigs of of storage (i.e. your usual embedded Linux SOC) matters.

> But perhaps I'm missing an important detail!

I don't think you're missing too much in context. As stated this was more of a curious side-project than a priority.

- With Docker, everything is quite well self-contained in the container image, but the kernel differs at runtime based on the Docker host running the container.
- Size wise I'm only interested in the image itself, the host system and kernel aren't too important there, but goal wise it was to minimize the binary size of the HTTP client.
- Disk and memory capacity aren't major concerns to resolve here either.
  - It was just from a talk with someone about how `wget` was about 4MB (binary + other shared libs linked) in addition to the weight of glibc + openssl.
    - That all adds up if you're only providing a container with your own small service binary of similar size or smaller, but just want to add an executable like an HTTP request for a healthcheck endpoint (_Docker feature built-in to the image performs a healthcheck via a command, service already has a healthcheck endpoint_).
  - `curl` IIRC was slightly larger than that and some Rust and Go alternatives had 8MB static builds released (_that I could compile down to approx 4MB_).
  - Eventually I found `httpget` which came about for the same reasons, and they distribute 530KB (HTTP only) and 1.2MB (HTTPS via Rustls) static builds on GH Releases and DockerHub images. That uses `minreq` and my custom build flags brings those down to 130KB / 770KB respectively.

As I've been on an optimizing binge for reducing much larger binaries lately and also went through that "Hello world" process recently I was happy with the results but curious if it could be pushed further.

- I then found `edge-http` as one of the promising leads towards achieving that, but soon realized nobody has yet to tackle a `no_std` HTTP client for amd64 (_probably because there is little incentive to do so_).
- I figured `rustix` might help, and not long after that I opened this issue to get feedback from someone who knows what they're talking about :)

So that's the short journey and original motivation. More of a "can this be pushed to a smaller size?" for the sake of it, rather than an actual need, and establishing how much effort that would actually be.

---

> The best way to implement this is simply in the form of a `edge-nal-rustix` crate, that implements the `edge-nal` abstractions by going straight into `rustix` and thus straight into the kernel.

So I think this is the key takeaway I was after.

I wanted to open this issue here while this was all still fresh in my mind. I'm not sure when I'll have time to come back and tackle this but it could be fun when I do 😎

Thanks for the insights! I'll close the issue since there isn't anything actionable on your end and I know now how to proceed with this 🚀
